config/routes.rb
Rails.application.routes.draw do
	root to: 'books#index'
	  devise_for :users

  resources :authors
  resources :books do
  resources :reviews
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :isbn, :genre, :publish_date, :num_page, :image_url, :author_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date %>
  </div>

  <div class="field">
    <%= form.label :num_page %>
    <%= form.text_field :num_page %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.select :author_id, options: Author.all.map { |author| [author.full_name, author.id] } %>
  </div>

  <div class="actions">
    <%= form.submit class: "button-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<header class="page-header">
  <div class="header-block-container">
    <h1>Books</h1>
  <% if current_user.present? %>
<%= link_to '+ New Book', new_book_path, class: 'button-white' %>
<% end %>
</div>
</header>

<section class="book-block-container">

  <% @books.each do |book| %>
  <div class="books">
  <div class="book-cover">
    <% if book.image_url %>
    <%= image_tag book.image_url %>
    <% end %>
  </div>
  <div class= "text-block">
    <h5><%= link_to book.title, book_path(book) %></h5>
    <h6><%= link_to book.author.full_name, author_path(book.author) %></h6>
  </div>
  </div>
<% end %>

</section>

app/views/books/new.html.erb
<header class="page-header">
  <div class="header-block-container">
<h1>New Book</h1>
<%= link_to 'Back', books_path, class: 'button-white-outline' %>
</div>
</header>

<div class="form-block-container"
<div class="card">
<%= render 'form', book: @book %>
</div>
</div>

app/views/books/show.html.erb
]<section class="book-wrapper">
  <div class="book-block-container">
    <div class="book-cover">
      <% if @book.image_url %>
        <%= image_tag @book.image_url %>
      <% end %>
      <div class= "text-block">
        <br>
        <br>
        <h1><%= @book.title %></h1>
        <h6><%= link_to @book.author.full_name, author_path(@book.author) %></h6>
        <br>
        <br>
        <p><%= @book.description %></p>
        <% if current_user.present? %>
         <%= link_to "Write a Review", new_book_review_path(@book), class: 'button-primary' %>
         <%= link_to 'Edit', edit_book_path(@book) %>
        <% end %>
    </div>
  </div>
</section>

<section>
  <div class="reviews-block-container">
    <h3>Reviews (<%= @book.reviews.size %>)</h3>
    <div class="reviews">
      <% @book.reviews.each do |review| %>
        <div class="review">
          <div class="user-initials">
            <%= review.user.initials %>
          </div>
          <div class="text-block">
            <div class="user-name">
              <strong><%= review.user.full_name %></strong>
            </div>
            <div class="rating-stars">
              <%= image_tag("#{review.rating}-stars.svg") %>
              <div class="timestamp">
                <%= review.created_at.strftime('%m/%d/%Y') %>
              </div>
            </div>
          </div>
          <div class="description">
            <%= review.comment %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </section>